<?php

namespace App\Services;

use App\Models\Channel;
use App\Models\Setting;
use App\Models\Warning;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ChannelService
{
    public function __construct(private YtDlpWrapper $ytDlpWrapper) {}

    /**
     * Download and store channel images (avatar, banner, fanart)
     * using yt-dlp based on Pinchflat's strategy.
     */
    public function fetchAndStoreChannelImages(Channel $channel): void
    {
        $tempDir = storage_path('app/temp/'.Str::random(16));
        mkdir($tempDir, 0755, true);

        // Define temp output path for images
        $outputPath = $tempDir.'/source_image.%(ext)s';

        $ytDlp = config('services.ytdlp_path', base_path('bin/yt-dlp'));

        $delay = Setting::ytdlpDelaySeconds();
        $sleepArgs = $delay > 0 ? "--sleep-requests {$delay} " : '';

        // 1. Run yt-dlp: --skip-download is CRUCIAL to not download videos
        // --playlist-items 0 gets channel level details
        // --write-info-json saves metadata to a .info.json file
        $command = "{$ytDlp} --skip-download --no-playlist --playlist-items 0 --write-all-thumbnails --convert-thumbnails jpg --write-info-json {$sleepArgs}--output ".escapeshellarg($outputPath).' '.escapeshellarg($channel->url).' 2>&1';

        [$output, $resultCode] = $this->ytDlpWrapper->runCommand($command, 90);

        if ($resultCode !== 0) {
            $message = "Failed to fetch channel images for {$channel->name} ({$channel->url}).";
            Log::error($message.' Code: '.$resultCode.'. Output: '.implode("\n", $output));
            Warning::log('channel_images_fetch_failed', $message, implode("\n", $output));
            $this->cleanup($tempDir);

            return;
        }

        // Find the generated JSON file
        $jsonFiles = glob($tempDir.'/*.info.json');
        if (empty($jsonFiles)) {
            $message = "Metadata JSON not created for {$channel->name} ({$channel->url}).";
            Log::error($message);
            Warning::log('channel_images_fetch_failed', $message);
            $this->cleanup($tempDir);

            return;
        }

        $jsonPath = $jsonFiles[0];
        $jsonContent = file_get_contents($jsonPath);
        $metadata = json_decode($jsonContent, true);

        if (! $metadata || ! isset($metadata['thumbnails'])) {
            $message = "Failed to parse channel metadata JSON for {$channel->name} ({$channel->url}).";
            Log::error($message);
            Warning::log('channel_images_fetch_failed', $message, $jsonContent);
            $this->cleanup($tempDir);

            return;
        }

        // 3. Process images
        $channelDir = 'channels/'.$channel->id;
        Storage::disk('public')->makeDirectory($channelDir);

        $thumbnails = $metadata['thumbnails'] ?? [];
        $processedImages = [];

        foreach ($thumbnails as $thumb) {
            $id = $thumb['id'] ?? '';
            // Match the thumbnail file generated by yt-dlp
            $sourceFile = $tempDir.'/source_image.'.($id ?: ($thumb['width'] ?? 'unknown')).'.jpg';
            if (! file_exists($sourceFile)) {
                continue;
            }

            $targetPath = '';

            if ($id === 'avatar_uncropped') {
                $targetPath = $channelDir.'/poster.jpg';
            } elseif ($id === 'banner_uncropped') {
                $targetPath = $channelDir.'/fanart.jpg';
            } elseif (isset($thumb['width'], $thumb['height']) && $thumb['height'] > 0 && ($thumb['width'] / $thumb['height']) > 3) {
                $targetPath = $channelDir.'/banner.jpg';
            }

            if ($targetPath && ! isset($processedImages[basename($targetPath, '.jpg')])) {
                Storage::disk('public')->put($targetPath, file_get_contents($sourceFile));
                $processedImages[basename($targetPath, '.jpg')] = $targetPath;
            }
        }

        // Fallback: If no poster, use best available thumbnail
        if (! isset($processedImages['poster'])) {
            usort($thumbnails, fn ($a, $b) => ($b['width'] ?? 0) <=> ($a['width'] ?? 0));
            foreach ($thumbnails as $thumb) {
                $sourceFile = $tempDir.'/source_image.'.($thumb['id'] ?: ($thumb['width'] ?? 'unknown')).'.jpg';
                if (file_exists($sourceFile)) {
                    $path = $channelDir.'/poster.jpg';
                    Storage::disk('public')->put($path, file_get_contents($sourceFile));
                    $processedImages['poster'] = $path;
                    break;
                }
            }
        }

        // Persist which images actually landed on disk so views can trust these columns
        // instead of stat-ing banner.jpg/fanart.jpg on every render.
        $channel->update([
            'banner_path' => $processedImages['banner'] ?? null,
            'fanart_path' => $processedImages['fanart'] ?? null,
        ]);

        Log::info("Channel images processed for {$channel->name}: ".json_encode($processedImages));

        $this->cleanup($tempDir);
    }

    /**
     * Clean up temporary directory and files
     */
    private function cleanup(string $dir): void
    {
        if (file_exists($dir)) {
            exec('rm -rf '.escapeshellarg($dir));
        }
    }
}
